# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.CharField(max_length=64)),
                ('slug', models.SlugField(default='xxx', unique=True)),
                ('name', models.CharField(max_length=64)),
                ('big_image', models.ImageField(blank=True, upload_to='art_big/')),
                ('description', models.TextField()),
                ('unit_price', models.FloatField(default=0.0, verbose_name='Unit Price')),
                ('stock', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
            options={
                'verbose_name': 'Art',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Print Support Size',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.CharField(max_length=64)),
                ('slug', models.SlugField(default='xxx', unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('unit_price', models.FloatField(default=0.0, verbose_name='Unit Price')),
                ('vendor_price', models.FloatField(default=0.0, verbose_name='Vendor Price')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
            options={
                'verbose_name': 'Print Support',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='size',
            name='support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Support'),
        ),
        migrations.AddField(
            model_name='art',
            name='tags',
            field=models.ManyToManyField(to='product.Tag'),
        ),
    ]
